apiVersion: v1
kind: Template
labels:
  template: configure-projects
metadata:
  name: configure-projects
objects:

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: argocd-edit-role
    namespace: ${TARGET_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: ${ARGOCD_NAMESPACE}

parameters:

- name: ARGOCD_NAMESPACE
  required: true
- name: TARGET_NAMESPACE
  required: true